/** Generated from docs/architecture/application-api.sprint7.openapi.json (Sprint 8 contract). */
export const apiContractVersion = "s8.0" as const;
export const generatedOperationIds = [
  "answerProjectContextQuestion",
  "candidate_edit_options_v1_projects__handle__candidate_edit_options_get",
  "captureQuickNote",
  "checkLlmConnection",
  "commitNoteDraft",
  "confirmCandidate",
  "confirmSelectedCandidate",
  "createNoteDraft",
  "editStructuredCandidate",
  "expandProjectGraph",
  "extractQuickNote",
  "getCandidateHistory",
  "getGraphNodeDetail",
  "getGraphNodeEvidence",
  "getGraphNodeLifecycle",
  "getKnowledgeEvidence",
  "getLiveness",
  "getProjectGraph",
  "getProjectKnowledgeDetail",
  "getProjectKnowledgeEvidence",
  "getProjectOverview",
  "getReadiness",
  "importNoteText",
  "listCandidateQueue",
  "listCurrentKnowledge",
  "listProjectKnowledge",
  "listProjects",
  "listStructuredNotes",
  "readLlmProfile",
  "readNoteDraft",
  "readProject",
  "readStructuredNote",
  "rebuildProjectInference",
  "rejectCandidate",
  "rejectSelectedCandidate",
  "removeLlmProfile",
  "rotateLlmCredential",
  "selectProject",
  "updateNoteDraft",
  "validateCandidate",
  "validateSelectedCandidate",
  "writeLlmProfile",
] as const;
